import React from "react";

const Privacy = () => {
  return (
    <div className="h-fit text-xs font-thin leading-5 text-slate-800">
      <h4 className="text-xl mb-2">Privacy</h4>
      <p>Privacy Policy</p>
      <p className="mb-3 italic">
        *Please note that this privacy notice was generated by chatGPT
      </p>
      <p>
        This Privacy Policy describes how we collect, use, and protect your
        personal information when you sign up for news and updates on our
        website.
      </p>
      <p>
        <b>1. Information We Collect</b>
      </p>
      <p>
        When you sign up for news and updates, we may collect the following
        information:
      </p>
      <p>Your email address.</p>
      <p>
        <b>2. How We Use Your Information</b>
      </p>
      <p>We use the information you provide for the following purposes:</p>
      <p>
        To send you news, updates, and other information related to our website.
      </p>
      <p>To improve our website and user experience.</p>
      <p>
        <b>3. Data Security</b>
      </p>
      <p>
        We are committed to protecting the security of your information. We
        implement reasonable and appropriate security measures to safeguard your
        data. However, please be aware that no data transmission over the
        internet can be guaranteed to be 100% secure
      </p>
      .
      <p>
        <b>4. Sharing Your Information</b>
      </p>
      <p>
        We do not share your personal information with third parties except:
      </p>
      <p>With your explicit consent.</p>
      <p>When required by law or to protect our rights.</p>
      <p>
        <b>5. Cookies</b>
      </p>
      <p>
        We may use cookies to enhance your experience on our website. You can
        adjust your browser settings to refuse cookies or alert you when a
        cookie is being sent.
      </p>
      <p>
        <b>6. Your Choices</b>
      </p>
      <p>
        You can update your preferences or unsubscribe from our mailing list at
        any time by clicking the unsubscribe link in our emails or contacting us
        directly.
      </p>
      <p>
        <b>7. Changes to this Privacy Policy</b>
      </p>
      <p>
        We may update this Privacy Policy from time to time. The updated version
        will be posted on our website with the revised Last Updated date.
      </p>
      <p>
        <b>8. Contact Us</b>
      </p>
      <p>
        If you have any questions or concerns about our Privacy Policy, please
        contact us.
      </p>
      <p>
        By signing up for news and updates on our website, you agree to the
        terms of this Privacy Policy.
      </p>
    </div>
  );
};

export default Privacy;
